spring.application.name=seal-server
seal.admin.username=${SEAL_ADMIN_USERNAME}
seal.admin.password=${SEAL_ADMIN_PASSWORD}
spring.datasource.url=${NEON_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.config.import=optional:file:./config/neon.properties
server.port=${PORT:8080}
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.jpa.open-in-view=false
